# default-layout
TagLine: The meeting place for professional Haskell programmers
Overview: Overview
Groups: Groups
FindAHaskeller: Find a Haskeller
FindAJob: Find a Job
Bling: Bling
FAQ: FAQ
NewsArchive: News Archive
BrowseSkills: Browse Skills
YourProfile: Your Profile
Logout: Logout
Login: Login
WelcomeUser name@Text: Welcome #{name}
IAmAHaskeller: I'm a Haskeller!
LoginWith: Login with

#teams
ExistingGroups: Existing Special Interest Groups
AddGroupLong: Add new special interest group
AddGroupShort: Add Group

#polls
Polls: Polls
NoPolls: No polls have been created.
PollAsked time@UTCTime: Asked on #{prettyTime time}
