# default-layout
TagLine: Le lieu de la rencontre pour programmeurs Haskell professionnels
Overview: Aperçu
Groups: Groupes
FindAHaskeller: Trouver un Haskeller
FindAJob: Trouver un emploi
Bling: Bling
FAQ: FAQ
NewsArchive: Toutes les nouvelles
BrowseSkills: Parcourir compétences
YourProfile: Votre profil
Logout: Déconnexion
Login: Connexion
WelcomeUser name@Text: Bienvenue, #{name}
IAmAHaskeller: Je suis un Haskeller !
LoginWith: Connexion avec

#teams
ExistingGroups: Les groupes d'intérêts spéciaux existants
AddGroupLong: Ajouter un nouvelle groupe d'intérêt spécial
AddGroupShort: Ajouter un groupe

#polls
Polls: Sondages
NoPolls: Aucune sondage n'a été effectué.
PollAsked time@UTCTime: Demandé à #{prettyTime time}
