# default-layout
TagLine: Место встречи профессиональных Хаскель–программистов
Overview: Обзор
Groups: Группы
FindAHaskeller: Найти Хаскелера
FindAJob: Найти работу
Bling: Мишура
FAQ: ЧаВо
NewsArchive: Архив новостей
BrowseSkills: Просмотреть навыки
YourProfile: Ваш профиль
Logout: Выйти
Login: Войти
WelcomeUser name@Text: Добро пожаловать, #{name}
IAmAHaskeller: Я Хаскелер!
LoginWith: Войти с помощью

#teams
ExistingGroups: Существующие группы по интересам
AddGroupLong: Добавить новую группу по интересам
AddGroupShort: Добавить группу

#polls
Polls: Опросы
NoPolls: Ни одного опроса не было создано.
PollAsked time@UTCTime: Опрос от #{prettyTime time}
