# default-layout
TagLine: Mötesplatsen för professionella haskellprogrammerare
Overview: Översikt
Groups: Grupper
FindAHaskeller: Hitta en Haskeller
FindAJob: Hitta ett jobb
Bling: Bling
FAQ: FAQ
NewsArchive: Nyhetsarkiv
BrowseSkills: Bläddra bland färdigheter
YourProfile: Din profil
Logout: Logga ut
Login: Logga in
WelcomeUser name@Text: Välkommen #{name}
IAmAHaskeller: Jag är en Haskeller!
LoginWith: Logga in med

#teams
ExistingGroups: Existerande intressegrupper
AddGroupLong: Lägg till ny intressegrupp
AddGroupShort: Lägg till grupp

#polls
Polls: Omröstning
NoPolls: Inga omröstningar har skapats
PollAsked time@UTCTime: Frågat den #{prettyTime time}
