# default-layout
TagLine: Место встречи профессиональных Haskell-программистов
Overview: Обзор
Groups: Группы
FindAHaskeller: Найти Haskeller'а
FindAJob: Найти работу
Bling: Мишура
FAQ: ЧаВо
NewsArchive: Архив новостей
BrowseSkills: Просмотреть навыки
YourProfile: Ваш профиль
Logout: Выйти
Login: Войти
WelcomeUser name@Text: Добро пожаловать, #{name}
IAmAHaskeller: Я Haskeller!
LoginWith: Войти с помощью

#teams
ExistingGroups: Существующие группы по интересам
AddGroupLong: Добавить новую группу по интересам
AddGroupShort: Добавить группу

#polls
Polls: Голосования
NoPolls: Ни одного опроса не было создано.
PollAsked time@UTCTime: Голосование от #{prettyTime time}
