# default-layout
TagLine: Місце зустрічі професійних Haskell-программістів
Overview: Огляд
Groups: Группи
FindAHaskeller: Знайти Haskeller'а
FindAJob: Знайти роботу
Bling: Мішура
FAQ: ЧЗП (Часто Запитувані Питання)
NewsArchive: Архів новин
BrowseSkills: Продивитися навички
YourProfile: Ваш профіль
Logout: Вийти
Login: Увійти
WelcomeUser name@Text: Ласкаво просимо, #{name}
IAmAHaskeller: Я Haskeller!
LoginWith: Увійти за допомогою

#teams
ExistingGroups: Існуючі групи по інтересах
AddGroupLong: Додати нову групу по інтересах
AddGroupShort: Додати групу

#polls
Polls: Голосування
NoPolls: Жодного опитування не було створено.
PollAsked time@UTCTime: Опитування від #{prettyTime time}
